os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "10.13.0"
sudo: required
cache:
  directories:
    - node
    - node_modules
env:
  global:
    - NODE_VERSION=10.13.0
    - IMAGE=dega/web
services:
  - docker
before_install:
  - nvm install $NODE_VERSION
  - npm install -g npm
  - node -v
  - npm -v
install:
  - npm install
script:
  - npm run build
  - docker build -t $IMAGE .

deploy:
  provider: script
  script: bash ./cicd/deploy.sh
  on:
    branch: deshetti

after_success:
  #- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  #- docker push $IMAGE;
  #- if [[ $TRAVIS_BRANCH == "deshetti" ]] && [[ $TRAVIS_PULL_REQUEST == "false" ]]; then
  #  docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  #  docker push $IMAGE;
  #  fi

#docker push $IMAGE;
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
